[supervisord]
nodaemon=true
user=root

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx_err.log

[program:openhost]
command=node /app/src/server.js
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/openhost.log
stderr_logfile=/var/log/supervisor/openhost_err.log
environment=NODE_ENV="production"